// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Data.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    partial class NexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Data.Entities.Niche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ElevenLabsVoiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MusicDirectory")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("QueuePriority")
                        .HasColumnType("integer");

                    b.Property<string>("ScriptTone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Niches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElevenLabsVoiceId = "",
                            IsActive = true,
                            MusicDirectory = "Assets/Music/Finance",
                            Name = "Finance",
                            QueuePriority = 100,
                            ScriptTone = "Formal, authoritative",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            ElevenLabsVoiceId = "",
                            IsActive = true,
                            MusicDirectory = "Assets/Music/Tech",
                            Name = "Tech & AI",
                            QueuePriority = 100,
                            ScriptTone = "Dynamic, enthusiastic",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            ElevenLabsVoiceId = "",
                            IsActive = true,
                            MusicDirectory = "Assets/Music/Legal",
                            Name = "Legal & Court",
                            QueuePriority = 100,
                            ScriptTone = "Narrative, dramatic pauses",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.Trend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompetitorChannelId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CompetitorVideoId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NicheId")
                        .HasColumnType("integer");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<double>("ViewsPerHour")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("NicheId", "MeasuredAtUtc");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("LocalMediaPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MediaTagsJson")
                        .HasColumnType("text");

                    b.Property<int>("NicheId")
                        .HasColumnType("integer");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ScriptText")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NicheId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Trend", b =>
                {
                    b.HasOne("Nexus.Data.Entities.Niche", "Niche")
                        .WithMany("Trends")
                        .HasForeignKey("NicheId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nexus.Data.Entities.Video", "Video")
                        .WithMany("Trends")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Niche");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Video", b =>
                {
                    b.HasOne("Nexus.Data.Entities.Niche", "Niche")
                        .WithMany("Videos")
                        .HasForeignKey("NicheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niche");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Niche", b =>
                {
                    b.Navigation("Trends");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Video", b =>
                {
                    b.Navigation("Trends");
                });
#pragma warning restore 612, 618
        }
    }
}
